version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3434:3434"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://mongodb:27050/mignaly
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3434
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    depends_on:
      - mongodb
    restart: always
    networks:
      - mignaly-network

  mongodb:
    image: mongo:latest
    ports:
      - "27050:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_DATABASE=mignaly
    networks:
      - mignaly-network

networks:
  mignaly-network:
    driver: bridge

volumes:
  mongodb_data: